plugins {
    id 'java-library'
}

java {
    modularity.inferModulePath = true
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.1'
    testImplementation 'org.mockito:mockito-core:5.8.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.8.0'
    testImplementation 'org.assertj:assertj-core:3.24.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

// test task configuration moved below

compileJava {
    options.compilerArgs << '--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED'
    options.compilerArgs << '--add-exports=java.base/sun.nio.ch=ALL-UNNAMED'
    options.compilerArgs << '--enable-preview'
}

compileTestJava {
    options.compilerArgs << '--enable-preview'
}

test {
    jvmArgs '--enable-preview'
    useJUnitPlatform()
}
